### ISSUE TITLE
How to use it on Linux?

### ISSUE THREAD

**Issue by averri** [jcbvm/i18n-editor#71]
Tried to run with `java -jar i18n-editor.jar`, the following error occur:

```bash
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at java.awt.Toolkit.getEventQueue(Toolkit.java:1736)
	at java.awt.EventQueue.invokeLater(EventQueue.java:1294)
	at javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1295)
	at com.jvms.i18neditor.Main.main(Main.java:24)

```

**Comment by btd1337** [comment]
Are you using Java 8?

**Comment by tibistibi** [comment]
With my ubuntu 18.04 it works fine.
